apiVersion: v1
kind: Service
annotations:
  service.beta.openshift.io/serving-cert-secret-name: ibm-cloud-vpn-tls
metadata:
  name: ibm-cloud-vpn-webhook
  namespace: ibm-vpn-proxy
spec:
  selector:
    app: ibm-cloud-vpn-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443