apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "ibm-cloud-vpn-webhook.ibm-vpn-proxy.svc"
annotations:
  service.beta.openshift.io/inject-cabundle=true
webhooks:
- name: "ibm-cloud-vpn-webhook.ibm-vpn-proxy.svc"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "ibm-vpn-proxy"
      name: "ibm-cloud-vpn-webhook"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5